kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test1  #第1个集群
nodes:
  - role: control-plane
    image: kindest/node:v1.24.15
    extraPortMappings:
      - containerPort: 6443
        hostPort: 36443  #安全组开放
        protocol: tcp
      - containerPort: 31443
        hostPort: 31443  #安全组开放   这是karmada的 apiserver端口 ,装在 test1上的
        protocol: tcp
    extraMounts:
      - hostPath: /root/kind/node1-1
        containerPath: /files
  - role: worker
    image: kindest/node:v1.24.15
    extraMounts:
      - hostPath: /root/kind/node1-2
        containerPath: /files
networking:
  apiServerAddress: "192.168.67.99" # 云服务器内网地址
  apiServerPort: 6443
  podSubnet: "10.6.0.0/16" #自定义 pod IP 地址范围
  serviceSubnet: "10.96.0.0/16"
  kubeProxyMode: "ipvs"