kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test2  #第2个集群
nodes:
  - role: control-plane
    image: kindest/node:v1.24.15
    extraPortMappings:
      - containerPort: 6444
        hostPort: 46443  #安全组开放
        protocol: tcp
    extraMounts:
      - hostPath: /root/kind/node2-1
        containerPath: /files
  - role: worker
    image: kindest/node:v1.24.15
    extraMounts:
      - hostPath: /root/kind/node2-2
        containerPath: /files
networking:
  apiServerAddress: "192.168.67.99" # 云服务器内网地址
  apiServerPort: 6444
  podSubnet: "10.7.0.0/16" #自定义 pod IP 地址范围
  serviceSubnet: "10.97.0.0/16"
  kubeProxyMode: "ipvs"