apiVersion: v1
kind: ServiceAccount
metadata:
  name: gintools-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gintools-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "events", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gintools-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gintools-role
subjects:
- kind: ServiceAccount
  name: gintools-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gintools
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gintools
  template:
    metadata:
      labels:
        app: gintools
    spec:
      serviceAccountName: gintools-sa
      containers:
      - name: gintools
        image: your-registry/gintools:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: gintools-service
  namespace: default
spec:
  selector:
    app: gintools
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP