apiVersion: v1
kind: Pod
metadata:
  name: client-go-example
spec:
  serviceAccountName: default
  containers:
  - name: example
    image: registry.cn-hangzhou.aliyuncs.com/aitools/client-go-example:v1.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
